name: sffn
channels:
  - defaults
dependencies:
  - python=3.8
  - ipykernel
  - numpy
  - pytorch
  - scipy
  - matplotlib
  - tensorboard
  - cudatoolkit=10.1
  - torchvision
  - pylint
  - scikit-learn
