name: sffn
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - ipykernel
  - numpy
  - pytorch=1.6.0
  - scipy
  - matplotlib
  - tensorboard
  - cudatoolkit=10.1
  - torchvision=0.7.0
  - pylint
  - scikit-learn
